spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 7071



eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

info:
  app:
    name: "apiGateWay"
    description: "apiGateWay service "
    version: "1.0"