spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://mysql:3306/abolfazl
    username: root
    password: Am@0311865186
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

