spring:
  application:
    name: discount
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://mysql:3306/abolfazl
    username: root
    password: Am@0311865186
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    registry-fetch-interval-seconds: 5

resilience4j:
  circuitbreaker:
    instances:
      myClient:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 50
      mm:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 50
info:
  app:
    name: "discount"
    description: "discount service "
    version: "1.0"